#!/bin/bash
# Regression check: concurrent workflow operations across requirements remain race-safe.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
source "$SCRIPT_DIR/_project-root.sh"
PROJECT_ROOT="$(vibe_resolve_project_root)"
TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/concurrent-workflows-check.XXXXXX")"
CHECK_ROOT="$TMP_ROOT/check"
LOG_ROOT="$TMP_ROOT/logs"
START_RACE_LOG_1="$LOG_ROOT/start-race-1.log"
START_RACE_LOG_2="$LOG_ROOT/start-race-2.log"
START_A_LOG="$LOG_ROOT/start-a.log"
START_B_LOG="$LOG_ROOT/start-b.log"
STATUS_A_LOG="$LOG_ROOT/status-a.log"
STATUS_B_LOG="$LOG_ROOT/status-b.log"
MERGE_A_LOG="$LOG_ROOT/merge-a.log"
MERGE_B_LOG="$LOG_ROOT/merge-b.log"
DOCS_REGEN_LOG_1="$LOG_ROOT/docs-regen-1.log"
DOCS_REGEN_LOG_2="$LOG_ROOT/docs-regen-2.log"

cleanup() {
  if [ -d "$CHECK_ROOT/.git" ]; then
    while IFS= read -r wt_path; do
      [ -z "$wt_path" ] && continue
      if [ "$wt_path" != "$CHECK_ROOT" ] && [[ "$wt_path" == "$TMP_ROOT"/* ]]; then
        git -C "$CHECK_ROOT" worktree remove "$wt_path" --force >/dev/null 2>&1 || true
      fi
    done < <(git -C "$CHECK_ROOT" worktree list --porcelain 2>/dev/null | awk '/^worktree / {print $2}')
  fi

  rm -rf "$TMP_ROOT"
}
trap cleanup EXIT

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "FAIL: missing required command: $cmd" >&2
    exit 1
  fi
}

require_cmd jq
require_cmd git

mkdir -p "$CHECK_ROOT"
mkdir -p "$LOG_ROOT"
(
  cd "$PROJECT_ROOT"
  tar -cf - --exclude='.git' .
) | tar -xf - -C "$CHECK_ROOT"

git -C "$CHECK_ROOT" init -b main >/dev/null
git -C "$CHECK_ROOT" config user.email "concurrency-check@example.com"
git -C "$CHECK_ROOT" config user.name "Concurrency Workflow Check"
git -C "$CHECK_ROOT" add .
git -C "$CHECK_ROOT" commit -m "baseline snapshot" >/dev/null

cd "$CHECK_ROOT"

seed_fixture_requirement() {
  local req_id="$1"
  local req_name="$2"
  local created_at="$3"
  local slug

  slug="$(echo "$req_name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//; s/-$//')"

  jq --arg id "$req_id" --arg name "$req_name" --arg ts "$created_at" '
    .requirements += [{
      "id": $id,
      "name": $name,
      "description": "Synthetic concurrency regression fixture",
      "status": "PROPOSED",
      "priority": "LOW",
      "origin": "project",
      "createdAt": $ts,
      "updatedAt": $ts
    }]
  ' .requirement-manifest.json > .requirement-manifest.json.tmp
  mv .requirement-manifest.json.tmp .requirement-manifest.json

  cat > "docs/requirements/${req_id}-${slug}.md" <<EOF
# $req_name

**ID**: $req_id  
**Status**: PROPOSED  
**Priority**: LOW  
**Created**: $created_at  

## Description

Synthetic concurrency regression fixture.

## Success Criteria

- [ ] Fixture lifecycle can progress safely under concurrent workflow operations.

## Technical Notes

Generated by scripts/check-concurrent-workflows.sh for isolated regression coverage.

## Dependencies

(None)

## Worktree

(Will be populated when work starts: feature/REQ-ID-slug)
EOF
}

CANDIDATES=()
while IFS= read -r req_id; do
  [ -z "$req_id" ] && continue
  CANDIDATES+=("$req_id")
done < <(
  jq -r '.requirements[]
    | select((.status == "PROPOSED" or .status == "BACKLOG") and ((.worktreeId // "") == ""))
    | .id' .requirement-manifest.json
)

if [ "${#CANDIDATES[@]}" -lt 3 ]; then
  NEED_COUNT=$((3 - ${#CANDIDATES[@]}))
  FIXTURE_INDEX=1
  while [ "$FIXTURE_INDEX" -le "$NEED_COUNT" ]; do
    FIXTURE_REQ_ID="REQ-900000000000000$FIXTURE_INDEX"
    if jq -e --arg reqId "$FIXTURE_REQ_ID" '.requirements[] | select(.id == $reqId)' .requirement-manifest.json >/dev/null; then
      FIXTURE_INDEX=$((FIXTURE_INDEX + 1))
      continue
    fi

    seed_fixture_requirement \
      "$FIXTURE_REQ_ID" \
      "Synthetic concurrency fixture $FIXTURE_INDEX" \
      "2026-04-27T00:00:0${FIXTURE_INDEX}Z"

    CANDIDATES+=("$FIXTURE_REQ_ID")
    FIXTURE_INDEX=$((FIXTURE_INDEX + 1))
  done
fi

RACE_REQ="${CANDIDATES[0]}"
REQ_A="${CANDIDATES[1]}"
REQ_B="${CANDIDATES[2]}"

if [ "$REQ_A" = "$REQ_B" ] || [ "$RACE_REQ" = "$REQ_A" ] || [ "$RACE_REQ" = "$REQ_B" ]; then
  echo "FAIL: candidate requirement selection produced duplicates." >&2
  exit 1
fi

active_worktree_count_for_req() {
  local req_id="$1"
  jq --arg reqId "$req_id" '[.worktrees[]? | select(.status == "ACTIVE") | select((.requirementIds // []) | index($reqId))] | length' .worktree-manifest.json
}

req_status() {
  local req_id="$1"
  jq -r --arg reqId "$req_id" '.requirements[] | select(.id == $reqId) | .status // empty' .requirement-manifest.json
}

# 1) Same-REQ race: exactly one concurrent start-work should succeed.
set +e
bash scripts/start-work.sh "$RACE_REQ" >"$START_RACE_LOG_1" 2>&1 &
RACE_PID_1=$!
bash scripts/start-work.sh "$RACE_REQ" >"$START_RACE_LOG_2" 2>&1 &
RACE_PID_2=$!

wait "$RACE_PID_1"
RACE_STATUS_1=$?
wait "$RACE_PID_2"
RACE_STATUS_2=$?
set -e

RACE_SUCCESS=0
[ "$RACE_STATUS_1" -eq 0 ] && RACE_SUCCESS=$((RACE_SUCCESS + 1))
[ "$RACE_STATUS_2" -eq 0 ] && RACE_SUCCESS=$((RACE_SUCCESS + 1))

if [ "$RACE_SUCCESS" -ne 1 ]; then
  echo "FAIL: expected exactly one successful same-REQ start-work race for $RACE_REQ (statuses: $RACE_STATUS_1, $RACE_STATUS_2)." >&2
  echo "---- start-race-1.log ----" >&2
  cat "$START_RACE_LOG_1" >&2 || true
  echo "---- start-race-2.log ----" >&2
  cat "$START_RACE_LOG_2" >&2 || true
  exit 1
fi

if [ "$(active_worktree_count_for_req "$RACE_REQ")" -ne 1 ]; then
  echo "FAIL: same-REQ race produced invalid ACTIVE mapping count for $RACE_REQ." >&2
  exit 1
fi

if [ "$(req_status "$RACE_REQ")" != "IN_PROGRESS" ]; then
  echo "FAIL: expected $RACE_REQ to end IN_PROGRESS after same-REQ start-work race." >&2
  exit 1
fi

# 2) Cross-REQ concurrent start-work progression.
set +e
bash scripts/start-work.sh "$REQ_A" >"$START_A_LOG" 2>&1 &
PID_A=$!
bash scripts/start-work.sh "$REQ_B" >"$START_B_LOG" 2>&1 &
PID_B=$!

wait "$PID_A"
STATUS_A=$?
wait "$PID_B"
STATUS_B=$?
set -e

if [ "$STATUS_A" -ne 0 ] || [ "$STATUS_B" -ne 0 ]; then
  echo "FAIL: expected concurrent cross-REQ start-work to succeed for $REQ_A and $REQ_B." >&2
  echo "---- start-a.log ----" >&2
  cat "$START_A_LOG" >&2 || true
  echo "---- start-b.log ----" >&2
  cat "$START_B_LOG" >&2 || true
  exit 1
fi

if [ "$(active_worktree_count_for_req "$REQ_A")" -ne 1 ] || [ "$(active_worktree_count_for_req "$REQ_B")" -ne 1 ]; then
  echo "FAIL: concurrent cross-REQ start-work produced invalid ACTIVE mapping counts." >&2
  exit 1
fi

WT_ID_A="$(jq -r --arg reqId "$REQ_A" '.requirements[] | select(.id == $reqId) | .worktreeId // empty' .requirement-manifest.json)"
WT_ID_B="$(jq -r --arg reqId "$REQ_B" '.requirements[] | select(.id == $reqId) | .worktreeId // empty' .requirement-manifest.json)"

if [ -z "$WT_ID_A" ] || [ -z "$WT_ID_B" ] || [ "$WT_ID_A" = "$WT_ID_B" ]; then
  echo "FAIL: concurrent cross-REQ start-work did not yield distinct worktree IDs." >&2
  exit 1
fi

WT_PATH_A="$(jq -r --arg wt "$WT_ID_A" '.worktrees[] | select(.id == $wt) | .path // empty' .worktree-manifest.json | head -1)"
WT_PATH_B="$(jq -r --arg wt "$WT_ID_B" '.worktrees[] | select(.id == $wt) | .path // empty' .worktree-manifest.json | head -1)"

if [ -z "$WT_PATH_A" ] || [ -z "$WT_PATH_B" ] || [ ! -d "$WT_PATH_A" ] || [ ! -d "$WT_PATH_B" ]; then
  echo "FAIL: worktree paths missing for cross-REQ workflow progression." >&2
  exit 1
fi

# 3) Simulate implementation evidence, then advance both via concurrent status updates (work-on progression proxy).
for req_id in "$REQ_A" "$REQ_B"; do
  req_spec="$(find docs/requirements -maxdepth 1 -name "${req_id}-*.md" | head -1)"
  if [ -z "$req_spec" ]; then
    echo "FAIL: missing requirement spec for $req_id" >&2
    exit 1
  fi

done

SPEC_A="$(find docs/requirements -maxdepth 1 -name "${REQ_A}-*.md" | head -1)"
SPEC_B="$(find docs/requirements -maxdepth 1 -name "${REQ_B}-*.md" | head -1)"

echo "\n- Concurrency check evidence for $REQ_A" >> "$WT_PATH_A/$SPEC_A"
git -C "$WT_PATH_A" add "$SPEC_A"
git -C "$WT_PATH_A" commit -m "test: evidence for $REQ_A" >/dev/null

echo "\n- Concurrency check evidence for $REQ_B" >> "$WT_PATH_B/$SPEC_B"
git -C "$WT_PATH_B" add "$SPEC_B"
git -C "$WT_PATH_B" commit -m "test: evidence for $REQ_B" >/dev/null

set +e
bash scripts/update-requirement-status.sh "$REQ_A" CODE_REVIEW >"$STATUS_A_LOG" 2>&1 &
STATUS_PID_A=$!
bash scripts/update-requirement-status.sh "$REQ_B" CODE_REVIEW >"$STATUS_B_LOG" 2>&1 &
STATUS_PID_B=$!

wait "$STATUS_PID_A"
SET_STATUS_A=$?
wait "$STATUS_PID_B"
SET_STATUS_B=$?
set -e

if [ "$SET_STATUS_A" -ne 0 ] || [ "$SET_STATUS_B" -ne 0 ]; then
  echo "FAIL: concurrent status advancement to CODE_REVIEW failed." >&2
  echo "---- status-a.log ----" >&2
  cat "$STATUS_A_LOG" >&2 || true
  echo "---- status-b.log ----" >&2
  cat "$STATUS_B_LOG" >&2 || true
  exit 1
fi

if [ "$(req_status "$REQ_A")" != "CODE_REVIEW" ] || [ "$(req_status "$REQ_B")" != "CODE_REVIEW" ]; then
  echo "FAIL: expected both requirements to be CODE_REVIEW after concurrent advancement." >&2
  exit 1
fi

# Concurrent status updates can leave commit-side effects split across processes.
# Normalize repository state before merge checks.
if [ -n "$(git -C "$CHECK_ROOT" status --porcelain)" ]; then
  git -C "$CHECK_ROOT" add -A
  git -C "$CHECK_ROOT" commit -m "test: normalize state before concurrent merge checks" >/dev/null || true
fi

# 4) Execute worktree-merge for both requirements and verify lifecycle/doc consistency.
if ! bash scripts/worktree-merge.sh "$REQ_A" >"$MERGE_A_LOG" 2>&1; then
  echo "FAIL: worktree-merge failed for $REQ_A" >&2
  cat "$MERGE_A_LOG" >&2 || true
  exit 1
fi

if ! bash scripts/worktree-merge.sh "$REQ_B" >"$MERGE_B_LOG" 2>&1; then
  echo "FAIL: worktree-merge failed for $REQ_B" >&2
  cat "$MERGE_B_LOG" >&2 || true
  exit 1
fi

EXPECTED_FINAL_STATUS="MERGED"
if [ "$(jq -r '.requiresDeployment // true' .requirement-manifest.json)" = "false" ]; then
  EXPECTED_FINAL_STATUS="DEPLOYED"
fi

if [ "$(req_status "$REQ_A")" != "$EXPECTED_FINAL_STATUS" ] || [ "$(req_status "$REQ_B")" != "$EXPECTED_FINAL_STATUS" ]; then
  echo "FAIL: unexpected post-merge lifecycle status for concurrent workflow requirements (expected $EXPECTED_FINAL_STATUS)." >&2
  exit 1
fi

if [ "$(active_worktree_count_for_req "$REQ_A")" -ne 0 ] || [ "$(active_worktree_count_for_req "$REQ_B")" -ne 0 ]; then
  echo "FAIL: worktree-merge left ACTIVE mappings for merged requirements." >&2
  exit 1
fi

# 5) Concurrent docs regeneration should serialize safely (code-review side effect proxy).
# Force mkdir lock fallback so stale '*.lock.d' checks exercise the fallback path,
# even on systems where flock is available.
set +e
MANIFEST_LOCK_FORCE_MKDIR=1 bash scripts/regenerate-docs.sh >"$DOCS_REGEN_LOG_1" 2>&1 &
DOCS_PID_1=$!
MANIFEST_LOCK_FORCE_MKDIR=1 bash scripts/regenerate-docs.sh >"$DOCS_REGEN_LOG_2" 2>&1 &
DOCS_PID_2=$!

wait "$DOCS_PID_1"
DOCS_STATUS_1=$?
wait "$DOCS_PID_2"
DOCS_STATUS_2=$?
set -e

if [ "$DOCS_STATUS_1" -ne 0 ] || [ "$DOCS_STATUS_2" -ne 0 ]; then
  echo "FAIL: concurrent docs regeneration failed (statuses: $DOCS_STATUS_1, $DOCS_STATUS_2)." >&2
  echo "---- docs-regen-1.log ----" >&2
  cat "$DOCS_REGEN_LOG_1" >&2 || true
  echo "---- docs-regen-2.log ----" >&2
  cat "$DOCS_REGEN_LOG_2" >&2 || true
  exit 1
fi

LOCK_ROOT="$(git rev-parse --git-common-dir)/.manifest-locks"
if [ -d "$LOCK_ROOT" ] && find "$LOCK_ROOT" -type d -name '*.lock.d' -print -quit | grep -q .; then
  echo "FAIL: stale manifest lock fallback directories remained after concurrent docs regeneration." >&2
  find "$LOCK_ROOT" -type d -name '*.lock.d' >&2 || true
  exit 1
fi

# Keep a final single-pass regeneration to match existing downstream expectations.
bash scripts/regenerate-docs.sh >/dev/null

# 6) Manifest and docs consistency checks.
jq -e '.requirements | type == "array"' .requirement-manifest.json >/dev/null
jq -e '.worktrees | type == "array"' .worktree-manifest.json >/dev/null

jq -e '
  ([.worktrees[]? | select(.status == "ACTIVE") | .id] | length)
  ==
  ([.worktrees[]? | select(.status == "ACTIVE") | .id] | unique | length)
' .worktree-manifest.json >/dev/null

jq -e '
  ([.worktrees[]? | select(.status == "ACTIVE") | .path] | length)
  ==
  ([.worktrees[]? | select(.status == "ACTIVE") | .path] | unique | length)
' .worktree-manifest.json >/dev/null

if ! grep -Fq "$REQ_A" docs/STATUS.md || ! grep -Fq "$REQ_B" docs/STATUS.md; then
  echo "FAIL: docs/STATUS.md missing concurrent workflow requirement entries after regeneration." >&2
  exit 1
fi

if ! grep -Fq "$REQ_A" REQUIREMENTS.md || ! grep -Fq "$REQ_B" REQUIREMENTS.md; then
  echo "FAIL: REQUIREMENTS.md missing concurrent workflow requirement entries after regeneration." >&2
  exit 1
fi

echo "PASS: concurrent workflow regression checks passed (same-REQ race, cross-REQ progression, merge lifecycle, and docs/manifests consistency)."